export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
 
export const ADD_INDICATION = 'ADD_INDICATION';
export const GET_INDICATIONS = 'GET_INDICATIONS';
 
export const ADD_CONTRAINDICATION = 'ADD_CONTRAINDICATION';
export const GET_CONTRAINDICATIONS = 'GET_CONTRAINDICATIONS';
 
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
 
export const ADD_OPERATOR = 'ADD_OPERATOR';
export const GET_OPERATORS = 'GET_OPERATORS';

export const SET_TABLE = 'SET_TABLE';
 
