export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
 
export const ADD_INDICATION = 'ADD_INDICATION';
export const GET_INDICATIONS = 'GET_INDICATIONS';
export const EDIT_INDICATIONS = 'EDIT_INDICATIONS';
export const DELETE_INDICATIONS = 'DELETE_INDICATIONS';
 
export const ADD_CONTRAINDICATION = 'ADD_CONTRAINDICATION';
export const GET_CONTRAINDICATIONS = 'GET_CONTRAINDICATIONS';
export const EDIT_CONTRAINDICATIONS = 'EDIT_CONTRAINDICATIONS';
export const DELETE_CONTRAINDICATIONS = 'DELETE_CONTRAINDICATIONS';
 
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const EDIT_CATEGORIES = 'EDIT_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
 
export const ADD_OPERATOR = 'ADD_OPERATOR';
export const GET_OPERATORS = 'GET_OPERATORS';
export const EDIT_OPERATORS = 'EDIT_OPERATORS';
export const DELETE_OPERATORS = 'DELETE_OPERATORS';

export const SET_TABLE = 'SET_TABLE';
 
