export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
 
export const ADD_INDICATION = 'ADD_INDICATION';
export const GET_INDICATIONS = 'GET_INDICATIONS';
export const EDIT_INDICATIONS = 'EDIT_INDICATIONS';
export const DELETE_INDICATIONS = 'DELETE_INDICATIONS';
 
export const ADD_CONTRAINDICATION = 'ADD_CONTRAINDICATION';
export const GET_CONTRAINDICATIONS = 'GET_CONTRAINDICATIONS';
export const EDIT_CONTRAINDICATIONS = 'EDIT_CONTRAINDICATIONS';
export const DELETE_CONTRAINDICATIONS = 'DELETE_CONTRAINDICATIONS';
 
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const EDIT_CATEGORIES = 'EDIT_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
 
export const ADD_OPERATOR = 'ADD_OPERATOR';
export const GET_OPERATORS = 'GET_OPERATORS';
export const EDIT_OPERATORS = 'EDIT_OPERATORS';
export const DELETE_OPERATORS = 'DELETE_OPERATORS';

export const ADD_CAIXA = 'ADD_CAIXA';
export const GET_CAIXAS = 'GET_CAIXAS';
export const EDIT_CAIXAS = 'EDIT_CAIXAS';
export const DELETE_CAIXAS = 'DELETE_CAIXAS';

export const ADD_COMPRA = 'ADD_COMPRA';
export const GET_COMPRAS = 'GET_COMPRAS';
export const EDIT_COMPRAS = 'EDIT_COMPRAS';
export const DELETE_COMPRAS = 'DELETE_COMPRAS';

export const ADD_ITEM = 'ADD_ITEM';
export const GET_ITENS = 'GET_ITENS';
export const EDIT_ITENS = 'EDIT_ITENS';
export const DELETE_ITENS= 'DELETE_ITENS';

export const ADD_MOVIMENTO = 'ADD_MOVIMENTO';
export const GET_MOVIMENTOS = 'GET_MOVIMENTOS';
export const EDIT_MOVIMENTOS = 'EDIT_MOVIMENTOS';
export const DELETE_MOVIMENTOS = 'DELETE_MOVIMENTOS';

export const ADD_PAGAMENTO = 'ADD_PAGAMENTO';
export const GET_PAGAMENTOS = 'GET_PAGAMENTOS';
export const EDIT_PAGAMENTOS = 'EDIT_PAGAMENTOS';
export const DELETE_PAGAMENTOS = 'DELETE_PAGAMENTOS';

export const SET_TABLE = 'SET_TABLE';
export const SET_CAIXA = 'SET_CAIXA';
export const SET_COMPRA = 'SET_COMPRA';
export const SET_MOVIMENTO = 'SET_MOVIMENTO';
export const GET_ID_COMPRA = 'GET_ID_COMPRA';
export const GET_ID_CAIXA = 'GET_ID_CAIXA';
export const GET_ID_MOVIMENTO = 'GET_ID_MOVIMENTO';
 
